# Generated by Django 4.2.6 on 2023-12-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod4', '0003_alter_stock_symbol_alter_transaction_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
