# Generated by Django 4.2.6 on 2023-12-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod4', '0004_transaction_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_price',
        ),
    ]
