# Generated by Django 4.2.6 on 2023-12-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod4', '0006_alter_transaction_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
