# Generated by Django 4.2.7 on 2023-11-22 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 10, 15, 39, 659449, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
