# Generated by Django 4.2.7 on 2023-11-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod1', '0006_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='exp_date',
            field=models.DateField(),
        ),
    ]
