# Generated by Django 4.2.6 on 2023-12-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod1', '0007_billcategory_custombill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='exp_date',
            field=models.CharField(max_length=5),
        ),
    ]
