# Generated by Django 4.2.6 on 2023-11-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod1', '0003_alter_userprofile_options_alter_userprofile_managers_and_more'),
        ('mod1', '0007_alter_creditcard_exp_date'),
    ]

    operations = [
    ]
