# Generated by Django 4.2.7 on 2023-12-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod1', '0009_duedatereminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DueDateReminder',
        ),
    ]
